version: "3"
services:
  go-consumer:
    build: ./go-consumer
    ports:
      - "3000:3000"
    environment:
      - KAFKA_HOST=kafka:9092
      - RABBITMQ_HOST=rabbitmq:5672
    volumes:
      - ./go-consumer:/app
    depends_on:
      - kafka
  producer:
    build: ./go-producer
    ports:
      - "3001:3001"
    environment:
      - KAFKA_HOST=kafka:9092
      - RABBITMQ_HOST=rabbitmq:5672
    volumes:
      - ./go-producer:/app
    depends_on:
      - kafka
  zookeeper:
    image: "bitnami/zookeeper:3.8.0"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:2.8.1"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

    depends_on:
      - zookeeper
  rabbitmq:
    image: bitnami/rabbitmq:3.9.7
    environment:
      - RABBITMQ_USERNAME=username
      - RABBITMQ_PASSWORD=password
    ports:
      - "15672:15672"
      - "5672:5672"
